version: '3'

services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    networks:
      - cassandra

  web:
    build: .
    command: /bin/bash -c "cd testproject && wait-for-it cassandra:9042 -- python manage.py sync_cassandra && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    networks:
      - cassandra
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CASS_HOST=cassandra

networks:
  cassandra:
